version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Porta onde o NGINX ficará exposto
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mapeia o arquivo de configuração do NGINX
    depends_on:
      - app
    networks:
      public_net:
        ipv4_address: "150.165.37.203"  # IP para o NGINX

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - HUGGINGFACE_REPO_ID=${HUGGINGFACE_REPO_ID}
    depends_on:
      - db
    networks:
      public_net:
        ipv4_address: "150.165.37.204"  # IP fixo para o serviço `app`

  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistência de dados
    networks:
      public_net:
        ipv4_address: "150.165.37.205"  # IP fixo para o serviço `db`

volumes:
  postgres_data:

networks:
  public_net:
    driver: bridge
    ipam:
      config:
        - subnet: "150.165.37.0/24"  # Definindo a subrede para os IPs
    driver_opts:
      com.docker.network.bridge.name: "fala-texto-bridge-network"
