version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - HUGGINGFACE_REPO_ID=${HUGGINGFACE_REPO_ID}
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistência de dados

volumes:
  postgres_data:
